const $ = id => document.getElementById(id);
const DB = "caves-saint-jean-photos", STORE = "photos", KEY = "bi-caviste-saint-jean-v1";
let selected = null, photoBlob = null, products = [];
function catalogue() { try { products = JSON.parse(localStorage.getItem(KEY) || "null")?.state?.products || []; } catch { products = []; } }
function openDB() { return new Promise((resolve,reject) => { const request=indexedDB.open(DB,1); request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error); }); }
async function storage(mode, callback) { const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode); const req=callback(tx.objectStore(STORE)); req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close();}); }
function normalize(s) { return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(); }
function setMessage(text,error=false) { $('message').textContent=text;$('message').style.color=error?'#a22d37':'#286c42'; }
async function compress(file) { const bitmap=await createImageBitmap(file);const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.78)); }
function showMatches() { const q=normalize($('search').value.trim());const matches=q?products.filter(p=>normalize([p.name,p.domain,p.id,p.supplier].join(' ')).includes(q)).slice(0,30):[];$('results').hidden=!matches.length;$('results').replaceChildren(...matches.map(p=>{const b=document.createElement('button');b.type='button';b.textContent=`${p.name} · ${p.domain||p.id}`;const small=document.createElement('small');small.textContent=`${p.id} · ${p.volume||''} · stock ${p.stock??'à inventorier'}`;b.append(small);b.onclick=()=>choose(p);return b;})); }
function choose(p) { selected=p;$('search').value=`${p.name} · ${p.id}`;$('results').hidden=true;$('selection').hidden=false;$('selection').textContent=`Référence liée : ${p.id} · ${p.name}`;$('match').textContent=`${p.name} · ${p.domain||'Domaine non renseigné'} · ${p.volume||''} · ${p.vintage||'Millésime non renseigné'} · stock ${p.stock??'à inventorier'}`;if(!$('title').value)$('title').value=p.name;updateLinks(); }
function updateLinks() { const query=[selected?.name,selected?.domain,$('title').value].filter(Boolean).join(' ');$('web').href='https://www.google.com/search?q='+encodeURIComponent(query+' vin bouteille');$('barcode').href='https://www.google.com/search?q='+encodeURIComponent(query+' code barre EAN'); }
async function gallery() { const records=await storage('readonly',s=>s.getAll());records.sort((a,b)=>b.created-a.created);$('gallery').replaceChildren(...records.map(record=>{const d=document.createElement('div');d.className='photo';const img=document.createElement('img');img.loading='lazy';img.alt=record.title||'Bouteille';img.src=URL.createObjectURL(record.blob);img.onload=()=>URL.revokeObjectURL(img.src);const label=document.createElement('small');label.textContent=`${record.productId||'Sans référence'} · ${record.title||'Photo'}`;const remove=document.createElement('button');remove.type='button';remove.className='danger';remove.textContent='Supprimer';remove.onclick=async()=>{if(!confirm('Supprimer cette photo locale ?'))return;await storage('readwrite',s=>s.delete(record.id));await gallery();};d.append(img,label,remove);return d;})); }
$('file').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{photoBlob=await compress(file);const url=URL.createObjectURL(photoBlob);$('preview').src=url;$('preview').hidden=false;$('preview').onload=()=>URL.revokeObjectURL(url);$('size').textContent=`Image optimisée : ${Math.round(photoBlob.size/1024)} Ko`;setMessage('Photo prête à enregistrer.');}catch(e){setMessage('Impossible de lire cette photo : '+e.message,true);} };
$('search').oninput=()=>{selected=null;$('selection').hidden=true;showMatches();updateLinks();};$('title').oninput=updateLinks;
$('save').onclick=async()=>{if(!photoBlob){setMessage('Prends ou choisis une photo avant de l’enregistrer.',true);return;}try{const id=crypto.randomUUID();await storage('readwrite',s=>s.put({id,productId:selected?.id||null,title:$('title').value.trim(),notes:$('notes').value.trim(),blob:photoBlob,created:Date.now()}));setMessage(selected?`Photo liée à ${selected.id} et enregistrée sur cet appareil.`:'Photo conservée sans référence sur cet appareil.');await gallery();}catch(e){setMessage('Enregistrement impossible : '+e.message,true);} };
$('clear').onclick=()=>{selected=null;photoBlob=null;for(const id of ['file','search','title','notes'])$(id).value='';$('preview').hidden=true;$('selection').hidden=true;$('match').textContent='Choisis une référence pour voir ses informations actuelles.';setMessage('Prêt pour une nouvelle bouteille.');};
catalogue();if(!products.length)setMessage('Aucun catalogue sauvegardé sur cet appareil : ouvre d’abord le BI et enregistre-le avant de rechercher une référence.',true);updateLinks();gallery().catch(e=>setMessage('Stockage photo indisponible : '+e.message,true));
