const $ = id => document.getElementById(id);
const DB = "caves-saint-jean-photos", STORE = "photos", KEY = "bi-caviste-saint-jean-v1";
let selected = null, photoBlob = null, products = [], editing = null;
async function catalogue() {
  try { products = JSON.parse(localStorage.getItem(KEY) || "null")?.state?.products || []; } catch { products = []; }
  if (!products.length) {
    try { const response = await fetch('./catalog-default.json'); if (response.ok) products = await response.json(); }
    catch { /* Offline and no saved catalogue yet. */ }
  }
  $('catalog-count').textContent = products.length ? `${products.length} produits disponibles · tape un nom ou choisis dans la liste` : 'Catalogue indisponible sur cet appareil.';
  showMatches();
}
function openDB() { return new Promise((resolve,reject) => { const request=indexedDB.open(DB,1); request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error); }); }
async function storage(mode, callback) { const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode); const req=callback(tx.objectStore(STORE)); req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close();}); }
function normalize(s) { return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(); }
function setMessage(text,error=false) { $('message').textContent=text;$('message').style.color=error?'#a22d37':'#286c42'; }
async function compress(file) { const bitmap=await createImageBitmap(file);const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.78)); }
function showMatches() { const q=normalize($('search').value.trim());const matches=(q?products.filter(p=>normalize([p.name,p.domain,p.id,p.supplier].join(' ')).includes(q)):products).slice(0,30);$('results').hidden=!matches.length;$('results').replaceChildren(...matches.map(p=>{const b=document.createElement('button');b.type='button';b.textContent=`${p.name} · ${p.domain||p.id}`;const small=document.createElement('small');small.textContent=`${p.id} · ${p.volume||''} · stock ${p.stock??'à inventorier'}`;b.append(small);b.onclick=()=>choose(p);return b;})); }
function choose(p) { selected=p;$('search').value=`${p.name} · ${p.id}`;$('results').hidden=true;$('selection').hidden=false;$('selection').textContent=`Référence liée : ${p.id} · ${p.name}`;$('match').textContent=`${p.name} · ${p.domain||'Domaine non renseigné'} · ${p.volume||''} · ${p.vintage||'Millésime non renseigné'} · stock ${p.stock??'à inventorier'}`;if(!$('title').value)$('title').value=p.name;updateLinks(); }
function updateLinks() { const query=[selected?.name||$('title').value,selected?.domain,$('appellation').value,$('vintage').value].filter(Boolean).join(' ');$('web').href='https://www.google.com/search?q='+encodeURIComponent(query+' vin bouteille');$('barcode').href='https://www.google.com/search?q='+encodeURIComponent($('ean').value.trim()||query+' code barre EAN'); }
async function gallery() { const records=await storage('readonly',s=>s.getAll());records.sort((a,b)=>b.created-a.created);$('gallery').replaceChildren(...records.map(record=>{const d=document.createElement('div');d.className='photo';const img=document.createElement('img');img.loading='lazy';img.alt=record.title||'Bouteille';img.src=URL.createObjectURL(record.blob);img.onload=()=>URL.revokeObjectURL(img.src);const label=document.createElement('small');label.textContent=`${record.productId||'Sans référence'} · ${record.title||'Photo'}${record.vintage?' · '+record.vintage:''}`;const edit=document.createElement('button');edit.type='button';edit.className='secondary';edit.textContent='Reprendre';edit.onclick=()=>{editing=record;photoBlob=record.blob;selected=products.find(p=>p.id===record.productId)||null;for(const id of ['title','notes','vintage','appellation','ean'])$(id).value=record[id]||'';$('search').value=selected?`${selected.name} · ${selected.id}`:'';$('selection').hidden=!selected;if(selected)choose(selected);else $('match').textContent='Cherche une référence pour relier cette photo.';const url=URL.createObjectURL(record.blob);$('preview').src=url;$('preview').hidden=false;$('preview').onload=()=>URL.revokeObjectURL(url);$('size').textContent=`Image optimisée : ${Math.round(record.blob.size/1024)} Ko`;$('save').textContent='Enregistrer les modifications';setMessage('Photo reprise : complète la fiche ou relie-la à une référence.');updateLinks();window.scrollTo({top:0,behavior:'smooth'});};const remove=document.createElement('button');remove.type='button';remove.className='danger';remove.textContent='Supprimer';remove.onclick=async()=>{if(!confirm('Supprimer cette photo ?'))return;await storage('readwrite',s=>s.delete(record.id));window.dispatchEvent(new CustomEvent('cave-photo-deleted',{detail:{id:record.id}}));if(editing?.id===record.id)$('clear').click();await gallery();};d.append(img,label,edit,remove);return d;})); }
$('file').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{photoBlob=await compress(file);const url=URL.createObjectURL(photoBlob);$('preview').src=url;$('preview').hidden=false;$('preview').onload=()=>URL.revokeObjectURL(url);$('size').textContent=`Image optimisée : ${Math.round(photoBlob.size/1024)} Ko`;setMessage('Photo prête à enregistrer.');}catch(e){setMessage('Impossible de lire cette photo : '+e.message,true);} };
$('search').oninput=()=>{selected=null;$('selection').hidden=true;showMatches();updateLinks();};for(const id of ['title','appellation','vintage','ean'])$(id).oninput=updateLinks;
$('save').onclick=async()=>{if(!photoBlob){setMessage('Prends ou choisis une photo avant de l’enregistrer.',true);return;}try{const id=editing?.id||crypto.randomUUID();const record={id,productId:selected?.id||null,blob:photoBlob,created:editing?.created||Date.now()};for(const key of ['title','notes','vintage','appellation','ean'])record[key]=$(key).value.trim();await storage('readwrite',s=>s.put(record));window.dispatchEvent(new CustomEvent('cave-photo-changed',{detail:{id}}));editing=record;$('save').textContent='Enregistrer les modifications';setMessage(selected?`Photo liée à ${selected.id} et enregistrée.`:'Photo conservée sans référence.');await gallery();}catch(e){setMessage('Enregistrement impossible : '+e.message,true);} };
$('clear').onclick=()=>{selected=null;photoBlob=null;editing=null;for(const id of ['file','search','title','notes','vintage','appellation','ean'])$(id).value='';$('preview').hidden=true;$('size').textContent='';$('selection').hidden=true;$('match').textContent='Choisis une référence pour voir ses informations actuelles.';$('save').textContent='Enregistrer la photo';setMessage('Prêt pour une nouvelle bouteille.');updateLinks();};
window.addEventListener('pageshow',()=>{catalogue();});
const count=document.createElement('p');count.id='catalog-count';count.className='muted';count.textContent='Chargement du catalogue…';$('search').closest('.field').insertBefore(count,$('results'));
const createLink=document.createElement('a');createLink.href='./?newProduct=1';createLink.className='action secondary';createLink.textContent='＋ Créer un produit dans le BI';createLink.style.marginTop='10px';$('search').closest('.field').append(createLink);
window.addEventListener('cave-photos-synced',()=>gallery().catch(()=>{}));
catalogue();updateLinks();gallery().catch(e=>setMessage('Stockage photo indisponible : '+e.message,true));
