(() => {
 'use strict';
 const themes=[['soft','Lumière douce'],['dark','Cave sombre'],['vine','Vignoble'],['light','Clair classique']];
 function applyTheme(value){const theme=themes.some(([id])=>id===value)?value:'soft';document.documentElement.dataset.caveTheme=theme;try{localStorage.setItem('cave-display-theme',theme);}catch{}const meta=document.querySelector('meta[name=theme-color]');if(meta)meta.content={dark:'#1c181c',vine:'#deded0',soft:'#e8dfd2',light:'#f6f4f0'}[theme];}
 function decoration(){const n=el('div',{class:'cave-ornament','aria-hidden':'true'});n.innerHTML='<svg viewBox="0 0 220 90" fill="none" xmlns="http://www.w3.org/2000/svg"><g stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M8 68C42 62 44 29 91 23C110 20 123 25 135 15M51 51C31 48 29 31 31 23C45 24 56 33 51 51ZM74 30C65 14 73 6 85 4C88 19 87 24 74 30ZM98 23C102 10 115 8 123 11C117 25 110 29 98 23Z"/><path d="M86 30L88 38M155 11h10v22c0 8 10 10 10 21v25q0 5-5 5h-20q-5 0-5-5V54c0-11 10-13 10-21V11ZM153 8h14M145 55h30M145 71h30M192 42h21l-3 19q-1 8-8 8t-8-8l-2-19ZM202 69v14M193 84h18"/><g fill="currentColor" fill-opacity=".16"><circle cx="81" cy="45" r="7"/><circle cx="95" cy="45" r="7"/><circle cx="74" cy="57" r="7"/><circle cx="88" cy="57" r="7"/><circle cx="102" cy="57" r="7"/><circle cx="81" cy="69" r="7"/><circle cx="95" cy="69" r="7"/><circle cx="88" cy="81" r="7"/></g></g></svg>';return n;}
 const navLabels = ['Accueil','Produits & stock','Ventes & factures','Livraisons','Clients'];
 let tools, mobile, dialog, previousFocus;
 const account=()=>window.caveAccount||{role:'local'};
 const el=(tag,attrs={},text='')=>{const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));n.textContent=text;return n;};
 function menuItems(){return [...document.querySelectorAll('[data-sidebar="menu-button"]')];}
 function navigate(label){const target={'Accueil':'home','Produits & stock':'products','Ventes & factures':'sales','Livraisons':'orders','Clients':'clients'}[label];if(window.caveNavigate&&target){window.caveNavigate(target);window.scrollTo({top:0,behavior:'smooth'});return;}const item=menuItems().find(n=>n.textContent.trim()===label);if(item){item.click();document.querySelector('[data-slot="sheet-content"] button[aria-label="Close"]')?.click();window.scrollTo({top:0,behavior:'smooth'});}}
 function show(title,body){previousFocus=document.activeElement;dialog.hidden=false;dialog.querySelector('h2').textContent=title;dialog.querySelector('.cave-help-content').replaceChildren(body);dialog.querySelector('.cave-close').focus();}
 function close(){dialog.hidden=true;previousFocus?.focus();}
 function help(){const body=el('div');const sections=[['Vendre au comptoir','Accueil → Nouvelle vente. Recherchez les produits, indiquez les quantités et le règlement, puis validez.'],['Établir une facture','Accueil → Créer une facture. Choisissez le client, ajoutez les produits, vérifiez les prix et imprimez le document.'],['Suivre les bouteilles','Produits & stock permet de rechercher une référence, mettre à jour une fiche et saisir les entrées ou sorties. Photos permet d’ajouter une image depuis le téléphone.'],['Préparer une livraison','Livraisons regroupe les commandes à préparer et le suivi de leur livraison.'],['PC et téléphone','La même application s’adapte à l’écran. Connectez-vous avec votre compte sur chaque appareil. Sur iPhone : Safari → Partager → Sur l’écran d’accueil. Sur PC : utilisez Installer l’application si le navigateur le propose.'],['Utilisateur et administrateur','L’utilisateur gère produits, stocks, ventes, clients et livraisons. L’administrateur dispose aussi des réglages, sauvegardes et autorisations des comptes.'],['Pendant la démonstration','Sans connexion, l’application fonctionne localement. Les ventes saisies dans la cave connectée sont des opérations réelles. Le bouton Animation permet d’afficher l’accueil animé.']];for(const [t,d] of sections){body.append(el('h3',{},t),el('p',{},d));}show('Prendre en main la cave',body);}
 async function team(){if(account().role!=='admin')return;const body=el('div');body.append(el('p',{},'Chaque personne crée et confirme son compte, puis un administrateur autorise son adresse e-mail ici. Aucun e-mail n’est envoyé depuis cet écran.'));
 const form=el('form');const label=el('label',{},'Adresse e-mail du compte');const email=el('input',{type:'email',required:'',autocomplete:'off',placeholder:'prenom@exemple.fr'});label.append(email);const roleLabel=el('label',{},'Accès');const role=el('select');role.append(el('option',{value:'user'},'Utilisateur — activité quotidienne'),el('option',{value:'admin'},'Administrateur — réglages et accès'));roleLabel.append(role);const submit=el('button',{type:'submit'},'Autoriser ce compte');const message=el('p',{class:'cave-message','aria-live':'polite'});form.append(label,roleLabel,submit,message);const list=el('div');body.append(form,list);show('Gestion des accès',body);
 async function refresh(){const members=await window.caveTeamList();const table=el('table');const head=el('tr');head.append(el('th',{},'Compte'),el('th',{},'Accès'),el('th',{},''));table.append(head);for(const m of members){const row=el('tr');row.append(el('td',{},m.email),el('td',{},m.role==='admin'?'Administrateur':'Utilisateur'));const cell=el('td');if(m.user_id!==m.owner_id){const remove=el('button',{type:'button',class:'cave-member-remove'},'Retirer');remove.onclick=async()=>{if(!confirm('Retirer l’accès à la cave pour '+m.email+' ?'))return;try{await window.caveSetMember(m.email,'remove');await refresh();}catch(e){message.textContent=e.message;}};cell.append(remove);}row.append(cell);table.append(row);}list.replaceChildren(table);}
 form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;try{await window.caveSetMember(email.value.trim(),role.value);message.textContent='Accès enregistré. Le compte peut se reconnecter à la cave.';email.value='';await refresh();}catch(e){message.textContent=e.message;}finally{submit.disabled=false;}};try{await refresh();}catch(e){message.textContent=e.message;}}
 function refresh(){const top=document.querySelector('.topbar');if(!top)return;if(!tools){tools=el('div',{id:'cave-tools'});const badge=el('span',{class:'cave-role'});const animation=el('button',{type:'button','aria-pressed':'false'},'Animation');animation.onclick=()=>{const on=document.body.classList.toggle('cave-show-animation');animation.setAttribute('aria-pressed',String(on));};const guide=el('button',{type:'button'},'Aide');guide.onclick=help;const access=el('button',{type:'button','data-admin-only':''},'Gestion des accès');access.onclick=team;const themeLabel=el('label',{class:'cave-theme-label'},'Ambiance');const themeSelect=el('select',{id:'cave-theme-select','aria-label':'Ambiance visuelle'});for(const [id,name] of themes)themeSelect.append(el('option',{value:id},name));themeSelect.value=document.documentElement.dataset.caveTheme||'soft';themeSelect.onchange=()=>applyTheme(themeSelect.value);themeLabel.append(themeSelect);tools.append(badge,themeLabel,guide,animation,access);top.append(tools);}
 const cloud=document.getElementById('cloud-sync-button');if(cloud&&cloud.parentElement!==tools)tools.append(cloud);const photos=document.getElementById('photo-module-link');if(photos&&photos.parentElement!==tools)tools.append(photos);
 document.body.dataset.cavePage=window.caveCurrentPage||'home';const a=account();document.body.classList.toggle('cave-operator',a.role==='user');document.body.classList.toggle('cave-pending',a.role==='pending');const badgeText={admin:'Administrateur',user:'Utilisateur',pending:'Accès en attente',local:'Mode local'}[a.role]||'Mode local';if(tools.querySelector('.cave-role').textContent!==badgeText)tools.querySelector('.cave-role').textContent=badgeText;tools.querySelector('[data-admin-only]').hidden=a.role!=='admin';
 menuItems().forEach(n=>{if(/Réglages|sauvegarde/.test(n.textContent))n.toggleAttribute('data-admin-only',true);});
 const workspace=document.querySelector('.workspace');const home=document.querySelector('.quick-grid');let intro=document.querySelector('.cave-intro');if(home&&!intro){intro=el('div',{class:'cave-intro'});intro.append(el('strong',{},'Que souhaitez-vous faire ?'),el('span',{},'Commencez par une vente, une facture ou une livraison. Le catalogue et les clients restent accessibles dans le menu.'));intro.append(decoration());workspace.querySelector('.page-heading')?.after(intro);}if(!home&&intro)intro.remove();
 if(!mobile){mobile=el('nav',{id:'cave-mobile-nav','aria-label':'Navigation principale'});for(const label of navLabels){const b=el('button',{type:'button'},label==='Produits & stock'?'Stock':label==='Ventes & factures'?'Ventes':label);b.dataset.target=label;b.onclick=()=>navigate(label);mobile.append(b);}document.body.append(mobile);}
 for(const b of mobile.children){const original=menuItems().find(n=>n.textContent.trim()===b.dataset.target);if(original){if(!b.querySelector('svg')){const icon=original.querySelector('svg');if(icon)b.prepend(icon.cloneNode(true));}if(original.dataset.active==='true')b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}else{const target={'Accueil':'home','Produits & stock':'products','Ventes & factures':'sales','Livraisons':'orders','Clients':'clients'}[b.dataset.target];if(window.caveCurrentPage===target)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}}
 let pending=document.getElementById('cave-pending');if(!pending){pending=el('div',{id:'cave-pending',hidden:''});pending.append(el('h2',{},'Votre accès attend une autorisation'),el('p',{},'Un administrateur doit ajouter votre adresse dans Gestion des accès. Vous pouvez ouvrir Mon compte pour vous déconnecter.'));document.body.append(pending);}pending.hidden=a.role!=='pending';
 }
 function boot(){applyTheme(document.documentElement.dataset.caveTheme);window.addEventListener('storage',e=>{if(e.key==='cave-display-theme'){applyTheme(e.newValue);const select=document.getElementById('cave-theme-select');if(select)select.value=document.documentElement.dataset.caveTheme;}});dialog=el('div',{id:'cave-help',hidden:''});const card=el('section',{class:'cave-help-card',role:'dialog','aria-modal':'true','aria-labelledby':'cave-help-title'});const c=el('button',{type:'button',class:'cave-close','aria-label':'Fermer'},'Fermer');c.onclick=close;card.append(c,el('h2',{id:'cave-help-title'}),el('div',{class:'cave-help-content'}));dialog.append(card);dialog.onclick=e=>{if(e.target===dialog)close();};document.body.append(dialog);document.addEventListener('keydown',e=>{if(dialog.hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button,input,select,a')].filter(n=>!n.disabled&&!n.hidden);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
 let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(refresh,50);}).observe(document.getElementById('root'),{childList:true,subtree:true});window.addEventListener('cave-account-changed',refresh);refresh();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
