-- Réservation matériel — schéma Supabase V22
-- À exécuter dans un projet Supabase DÉDIÉ au Merlet.

create table if not exists public.team_members (
  email text primary key,
  display_name text,
  role text not null default 'member' check (role in ('member','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.material_reservation_state (
  id text primary key check (id = 'shared'),
  revision bigint not null default 0 check (revision >= 0),
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.material_reservation_conflicts (
  id bigint generated by default as identity primary key,
  detected_at timestamptz not null default now(),
  user_email text,
  local_revision bigint,
  remote_revision bigint,
  details jsonb not null default '{}'::jsonb
);

alter table public.team_members enable row level security;
alter table public.material_reservation_state enable row level security;
alter table public.material_reservation_conflicts enable row level security;

revoke all on table public.team_members from anon;
revoke all on table public.material_reservation_state from anon;
revoke all on table public.material_reservation_conflicts from anon;

grant select on table public.team_members to authenticated;
grant select, insert, update on table public.material_reservation_state to authenticated;
grant select, insert on table public.material_reservation_conflicts to authenticated;
grant usage, select on sequence public.material_reservation_conflicts_id_seq to authenticated;

drop policy if exists "team member can read own membership" on public.team_members;
create policy "team member can read own membership"
on public.team_members for select
to authenticated
using (active and lower(email) = lower(coalesce(auth.jwt()->>'email','')));

drop policy if exists "active team can read shared state" on public.material_reservation_state;
create policy "active team can read shared state"
on public.material_reservation_state for select
to authenticated
using (exists (
  select 1 from public.team_members tm
  where tm.active and lower(tm.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "active team can insert shared state" on public.material_reservation_state;
create policy "active team can insert shared state"
on public.material_reservation_state for insert
to authenticated
with check (id='shared' and exists (
  select 1 from public.team_members tm
  where tm.active and lower(tm.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "active team can update shared state" on public.material_reservation_state;
create policy "active team can update shared state"
on public.material_reservation_state for update
to authenticated
using (exists (
  select 1 from public.team_members tm
  where tm.active and lower(tm.email)=lower(coalesce(auth.jwt()->>'email',''))
))
with check (id='shared' and exists (
  select 1 from public.team_members tm
  where tm.active and lower(tm.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "active team can read conflicts" on public.material_reservation_conflicts;
create policy "active team can read conflicts"
on public.material_reservation_conflicts for select
to authenticated
using (exists (
  select 1 from public.team_members tm
  where tm.active and lower(tm.email)=lower(coalesce(auth.jwt()->>'email',''))
));

drop policy if exists "active team can log conflicts" on public.material_reservation_conflicts;
create policy "active team can log conflicts"
on public.material_reservation_conflicts for insert
to authenticated
with check (exists (
  select 1 from public.team_members tm
  where tm.active and lower(tm.email)=lower(coalesce(auth.jwt()->>'email',''))
));
